# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Zen Kitty Games
email: zenkittygames@gmail.com
description: Zen Kitty Games is a game development studio, creators of the relaxing puzzle game Zen Garden!
url: "http://zenkittygames.github.io"
twitter_username: ZenKittyGames
facebook_username: ZenKittyGames

# Build settings
markdown: kramdown
